export const ERROR_CODES = [
  "CARD_NOT_FOUND",
  "INSUFFICIENT_FLUX",
  "NOT_PLAYERS_TURN",
  "NO_ROOM_ID",
  "TOO_MANY_CARDS_IN_HAND",
  "CARD_NOT_ACTIVATABLE",
  "NOT_ENOUGH_FLUX",
] as const;

export const SUCCESS_CODES = ["GAME_ENDED"] as const;
