import { defineCardDefinition } from "../cards";

export const WATER_CARDS = defineCardDefinition({
  /***** RUNE - 1 *****/
  "0w0": {
    domain: "WATER",
    type: "RUNE",
    name: "Water Rune",
    description: "At the start of your turn, generate 1W",
    cost: 0,
    price: 10,
    triggers: {
      onTurnEnd: [
        { id: "flux.generate", args: { domain: "WATER", amount: 1 } },
      ],
    },
  },
  "0w1": {
    domain: "WATER",
    type: "CREATURE",
    name: "River Sprite",
    description: "",
    damage: 1,
    health: 2,
    activations: 0,
    cost: 1,
    price: 10,
    triggers: {},
  },
  "0w2": {
    domain: "WATER",
    type: "CREATURE",
    name: "Coral Guardian",
    description: "",
    damage: 2,
    health: 6,
    activations: 0,
    cost: 3,
    price: 10,
    triggers: {},
  },
  "0w3": {
    domain: "WATER",
    type: "CREATURE",
    name: "Frostfin Serpent",
    description: "",
    damage: 3,
    health: 4,
    activations: 0,
    cost: 5,
    price: 10,
    triggers: {},
  },
  "0w4": {
    domain: "WATER",
    type: "CREATURE",
    name: "Bloomtide Nymph",
    description: "",
    damage: 2,
    health: 4,
    activations: 0,
    cost: 5,
    price: 10,
    triggers: {},
  },
  "0w5": {
    domain: "WATER",
    type: "CREATURE",
    name: "Stormscale Ray",
    description: "",
    damage: 4,
    health: 3,
    activations: 0,
    cost: 5,
    price: 10,
    triggers: {},
  },
  "0w6": {
    domain: "WATER",
    type: "CREATURE",
    name: "Sapphire Elemental",
    description: "",
    damage: 10,
    health: 6,
    activations: 0,
    cost: 10,
    price: 10,
    triggers: {},
  },
  "0w7": {
    domain: "WATER",
    type: "SPELL",
    name: "Tidal Wave",
    description: "Destroy any non-water create with less than 3hp",
    activations: 0,
    cost: 5,
    price: 10,
    targets: ["selfCreatures", "opponentCreatures"],
    triggers: {
      onActivated: [
        {
          id: "target.destroy",
          args: {
            condition: {
              field: "health",
              modififer: "lessThan",
              value: 3,
            },
          },
        },
      ],
    },
  },
  "0w8": {
    domain: "WATER",
    type: "SPELL",
    name: "Freeze Ray",
    description: "",
    activations: 0,
    cost: 1,
    price: 10,
    targets: ["creature"],
    triggers: {
      onActivated: [
        {
          id: "target.conditions",
          args: {
            conditions: ["frozen"],
            chance: 1,
            length: 3,
          },
        },
      ],
    },
  },
  "0w9": {
    domain: "WATER",
    type: "SPELL",
    name: "Healing Rain",
    description: "",
    activations: 0,
    cost: 2,
    price: 10,
    triggers: {},
  },
});
