/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppGameRouteRouteImport } from './routes/_app/game/route'
import { Route as AppGameIndexRouteImport } from './routes/_app/game/index'
import { Route as AppHomeIndexRouteImport } from './routes/_app/_home/index'
import { Route as AppGameLobbyIndexRouteImport } from './routes/_app/game/lobby/index'

const AppGameRouteRoute = AppGameRouteRouteImport.update({
  id: '/_app/game',
  path: '/game',
  getParentRoute: () => rootRouteImport,
} as any)
const AppGameIndexRoute = AppGameIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppGameRouteRoute,
} as any)
const AppHomeIndexRoute = AppHomeIndexRouteImport.update({
  id: '/_app/_home/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppGameLobbyIndexRoute = AppGameLobbyIndexRouteImport.update({
  id: '/lobby/',
  path: '/lobby/',
  getParentRoute: () => AppGameRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/game': typeof AppGameRouteRouteWithChildren
  '/': typeof AppHomeIndexRoute
  '/game/': typeof AppGameIndexRoute
  '/game/lobby/': typeof AppGameLobbyIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AppHomeIndexRoute
  '/game': typeof AppGameIndexRoute
  '/game/lobby': typeof AppGameLobbyIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app/game': typeof AppGameRouteRouteWithChildren
  '/_app/_home/': typeof AppHomeIndexRoute
  '/_app/game/': typeof AppGameIndexRoute
  '/_app/game/lobby/': typeof AppGameLobbyIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/game' | '/' | '/game/' | '/game/lobby/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/game' | '/game/lobby'
  id:
    | '__root__'
    | '/_app/game'
    | '/_app/_home/'
    | '/_app/game/'
    | '/_app/game/lobby/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppGameRouteRoute: typeof AppGameRouteRouteWithChildren
  AppHomeIndexRoute: typeof AppHomeIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app/game': {
      id: '/_app/game'
      path: '/game'
      fullPath: '/game'
      preLoaderRoute: typeof AppGameRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/game/': {
      id: '/_app/game/'
      path: '/'
      fullPath: '/game/'
      preLoaderRoute: typeof AppGameIndexRouteImport
      parentRoute: typeof AppGameRouteRoute
    }
    '/_app/_home/': {
      id: '/_app/_home/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppHomeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/game/lobby/': {
      id: '/_app/game/lobby/'
      path: '/lobby'
      fullPath: '/game/lobby/'
      preLoaderRoute: typeof AppGameLobbyIndexRouteImport
      parentRoute: typeof AppGameRouteRoute
    }
  }
}

interface AppGameRouteRouteChildren {
  AppGameIndexRoute: typeof AppGameIndexRoute
  AppGameLobbyIndexRoute: typeof AppGameLobbyIndexRoute
}

const AppGameRouteRouteChildren: AppGameRouteRouteChildren = {
  AppGameIndexRoute: AppGameIndexRoute,
  AppGameLobbyIndexRoute: AppGameLobbyIndexRoute,
}

const AppGameRouteRouteWithChildren = AppGameRouteRoute._addFileChildren(
  AppGameRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppGameRouteRoute: AppGameRouteRouteWithChildren,
  AppHomeIndexRoute: AppHomeIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
