/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppLobbyIndexRouteImport } from './routes/_app/lobby/index'
import { Route as AppGame_oldIndexRouteImport } from './routes/_app/game_old/index'
import { Route as AppHomeIndexRouteImport } from './routes/_app/_home/index'

const AppLobbyIndexRoute = AppLobbyIndexRouteImport.update({
  id: '/_app/lobby/',
  path: '/lobby/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppGame_oldIndexRoute = AppGame_oldIndexRouteImport.update({
  id: '/_app/game_old/',
  path: '/game_old/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppHomeIndexRoute = AppHomeIndexRouteImport.update({
  id: '/_app/_home/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppHomeIndexRoute
  '/game_old/': typeof AppGame_oldIndexRoute
  '/lobby/': typeof AppLobbyIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AppHomeIndexRoute
  '/game_old': typeof AppGame_oldIndexRoute
  '/lobby': typeof AppLobbyIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app/_home/': typeof AppHomeIndexRoute
  '/_app/game_old/': typeof AppGame_oldIndexRoute
  '/_app/lobby/': typeof AppLobbyIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/game_old/' | '/lobby/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/game_old' | '/lobby'
  id: '__root__' | '/_app/_home/' | '/_app/game_old/' | '/_app/lobby/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppHomeIndexRoute: typeof AppHomeIndexRoute
  AppGame_oldIndexRoute: typeof AppGame_oldIndexRoute
  AppLobbyIndexRoute: typeof AppLobbyIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app/lobby/': {
      id: '/_app/lobby/'
      path: '/lobby'
      fullPath: '/lobby/'
      preLoaderRoute: typeof AppLobbyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/game_old/': {
      id: '/_app/game_old/'
      path: '/game_old'
      fullPath: '/game_old/'
      preLoaderRoute: typeof AppGame_oldIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/_home/': {
      id: '/_app/_home/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppHomeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  AppHomeIndexRoute: AppHomeIndexRoute,
  AppGame_oldIndexRoute: AppGame_oldIndexRoute,
  AppLobbyIndexRoute: AppLobbyIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
