/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as AppGameRouteRouteImport } from './routes/_app/game/route'
import { Route as AppSetupIndexRouteImport } from './routes/_app/setup/index'
import { Route as AppGameIndexRouteImport } from './routes/_app/game/index'
import { Route as AppHomeIndexRouteImport } from './routes/_app/_home/index'
import { Route as AppGameLobbyIndexRouteImport } from './routes/_app/game/lobby/index'
import { Route as AppGameLobbySingleRouteImport } from './routes/_app/game/lobby/single'

const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppGameRouteRoute = AppGameRouteRouteImport.update({
  id: '/game',
  path: '/game',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSetupIndexRoute = AppSetupIndexRouteImport.update({
  id: '/setup/',
  path: '/setup/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppGameIndexRoute = AppGameIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppGameRouteRoute,
} as any)
const AppHomeIndexRoute = AppHomeIndexRouteImport.update({
  id: '/_home/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppGameLobbyIndexRoute = AppGameLobbyIndexRouteImport.update({
  id: '/lobby/',
  path: '/lobby/',
  getParentRoute: () => AppGameRouteRoute,
} as any)
const AppGameLobbySingleRoute = AppGameLobbySingleRouteImport.update({
  id: '/lobby/single',
  path: '/lobby/single',
  getParentRoute: () => AppGameRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppHomeIndexRoute
  '/game': typeof AppGameRouteRouteWithChildren
  '/game/': typeof AppGameIndexRoute
  '/setup/': typeof AppSetupIndexRoute
  '/game/lobby/single': typeof AppGameLobbySingleRoute
  '/game/lobby/': typeof AppGameLobbyIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AppHomeIndexRoute
  '/game': typeof AppGameIndexRoute
  '/setup': typeof AppSetupIndexRoute
  '/game/lobby/single': typeof AppGameLobbySingleRoute
  '/game/lobby': typeof AppGameLobbyIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteRouteWithChildren
  '/_app/game': typeof AppGameRouteRouteWithChildren
  '/_app/_home/': typeof AppHomeIndexRoute
  '/_app/game/': typeof AppGameIndexRoute
  '/_app/setup/': typeof AppSetupIndexRoute
  '/_app/game/lobby/single': typeof AppGameLobbySingleRoute
  '/_app/game/lobby/': typeof AppGameLobbyIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/game'
    | '/game/'
    | '/setup/'
    | '/game/lobby/single'
    | '/game/lobby/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/game' | '/setup' | '/game/lobby/single' | '/game/lobby'
  id:
    | '__root__'
    | '/_app'
    | '/_app/game'
    | '/_app/_home/'
    | '/_app/game/'
    | '/_app/setup/'
    | '/_app/game/lobby/single'
    | '/_app/game/lobby/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRouteRoute: typeof AppRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/game': {
      id: '/_app/game'
      path: '/game'
      fullPath: '/game'
      preLoaderRoute: typeof AppGameRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/setup/': {
      id: '/_app/setup/'
      path: '/setup'
      fullPath: '/setup/'
      preLoaderRoute: typeof AppSetupIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/game/': {
      id: '/_app/game/'
      path: '/'
      fullPath: '/game/'
      preLoaderRoute: typeof AppGameIndexRouteImport
      parentRoute: typeof AppGameRouteRoute
    }
    '/_app/_home/': {
      id: '/_app/_home/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppHomeIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/game/lobby/': {
      id: '/_app/game/lobby/'
      path: '/lobby'
      fullPath: '/game/lobby/'
      preLoaderRoute: typeof AppGameLobbyIndexRouteImport
      parentRoute: typeof AppGameRouteRoute
    }
    '/_app/game/lobby/single': {
      id: '/_app/game/lobby/single'
      path: '/lobby/single'
      fullPath: '/game/lobby/single'
      preLoaderRoute: typeof AppGameLobbySingleRouteImport
      parentRoute: typeof AppGameRouteRoute
    }
  }
}

interface AppGameRouteRouteChildren {
  AppGameIndexRoute: typeof AppGameIndexRoute
  AppGameLobbySingleRoute: typeof AppGameLobbySingleRoute
  AppGameLobbyIndexRoute: typeof AppGameLobbyIndexRoute
}

const AppGameRouteRouteChildren: AppGameRouteRouteChildren = {
  AppGameIndexRoute: AppGameIndexRoute,
  AppGameLobbySingleRoute: AppGameLobbySingleRoute,
  AppGameLobbyIndexRoute: AppGameLobbyIndexRoute,
}

const AppGameRouteRouteWithChildren = AppGameRouteRoute._addFileChildren(
  AppGameRouteRouteChildren,
)

interface AppRouteRouteChildren {
  AppGameRouteRoute: typeof AppGameRouteRouteWithChildren
  AppHomeIndexRoute: typeof AppHomeIndexRoute
  AppSetupIndexRoute: typeof AppSetupIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppGameRouteRoute: AppGameRouteRouteWithChildren,
  AppHomeIndexRoute: AppHomeIndexRoute,
  AppSetupIndexRoute: AppSetupIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRouteRoute: AppRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
